# Generated by Django 4.2.7 on 2024-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marteai', '0002_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
