# Generated by Django 4.2.7 on 2024-01-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marteai', '0003_feedback_first_name_feedback_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
